databases:
  - name: prahari-db
    databaseName: prahari
    user: prahari
    plan: free
    postgresMajorVersion: 15

services:
  - type: web
    name: prahari-demo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: Prahari
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: prahari-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: prahari-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: prahari-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: prahari-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: prahari-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
